# =====================================================================
# FILE: backend/test_coordinator_agent.py
# DESCRIPTION: Comprehensive test suite for verifying the Coordinator Agent.
#              Uses NVIDIA Nemotron Planner mocks for self-contained execution.
# =====================================================================

import sys
import os
import json
from pathlib import Path
from PIL import Image, ImageDraw
from unittest.mock import patch, MagicMock

# Add the 'backend/' directory to the Python path
BACKEND_DIR = Path(__file__).resolve().parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.append(str(BACKEND_DIR))

from app.agents.coordinator_agent import process_request

def create_mock_leaf_image(output_path: Path) -> None:
    """Creates a simple green JPEG image for testing."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    img = Image.new("RGB", (200, 200), color=(34, 139, 34))
    draw = ImageDraw.Draw(img)
    draw.ellipse([80, 80, 120, 120], fill=(218, 165, 32))
    img.save(output_path, "JPEG")

def mock_generate_execution_plan(user_query, image_uploaded=False, gps_available=False, location_name=None, conversation_context=None):
    """Mocks the planner to return appropriate execution steps based on query content."""
    query_lower = user_query.lower()
    steps = []
    
    if "spot" in query_lower or "disease" in query_lower or "tomato leaves" in query_lower:
        steps.append({"step": len(steps) + 1, "agent": "disease", "action": "Diagnose leaf spots"})
    if "irrigate" in query_lower or "weather" in query_lower or "temperature" in query_lower:
        steps.append({"step": len(steps) + 1, "agent": "weather", "action": "Fetch weather advisory"})
    if "where am i" in query_lower or "coordinates" in query_lower:
        steps.append({"step": len(steps) + 1, "agent": "location", "action": "Determine location"})
        
    if not steps:
        steps.append({"step": 1, "agent": "crop", "action": "Provide general crop advice"})
        
    return {
        "steps": steps,
        "required_data": [],
        "response_tone": "general"
    }

async def mock_call_weather_mcp_tool(latitude, longitude):
    return {
        "temperature": 25.0,
        "humidity": 60,
        "precipitation": 0.0,
        "wind_speed": 10.0,
        "soil_temperature": 22.0,
        "soil_moisture": 0.3,
        "weather_condition": "Partly cloudy"
    }

async def mock_call_location_mcp_tool(latitude, longitude):
    return {
        "city": "Bhubaneswar",
        "district": "Khordha",
        "state": "Odisha",
        "country": "India",
        "formatted_location": "Bhubaneswar, Odisha, India"
    }

@patch("app.agents.coordinator_agent.call_weather_mcp_tool", new=mock_call_weather_mcp_tool)
@patch("app.agents.coordinator_agent.call_location_mcp_tool", new=mock_call_location_mcp_tool)
@patch("app.agents.coordinator_agent.generate_execution_plan", side_effect=mock_generate_execution_plan)
@patch("app.agents.weather_agent.get_weather")
@patch("app.agents.weather_agent.generate_text")
@patch("app.agents.crop_agent.generate_text")
@patch("app.agents.location_agent.generate_text")
@patch("app.services.response_generator.generate_text")
@patch("app.agents.disease_agent.analyze_image_with_nvidia")
@patch("app.agents.coordinator_agent.spell_service.correct_query", new=MagicMock(side_effect=lambda x: x))
@patch("app.agents.coordinator_agent.translator_service.translate_to_english", new=MagicMock(side_effect=lambda text, lang: text))
@patch("app.agents.coordinator_agent.translator_service.translate_from_english", new=MagicMock(side_effect=lambda text, lang: text))
def run_tests(mock_disease, mock_synth, mock_loc_llm, mock_crop_llm, mock_weather_llm, mock_get_weather, mock_planner) -> None:
    """Executes the suite of coordinator routing test cases."""
    
    mock_get_weather.return_value = {
        "current": {
            "temperature_2m": 25.0,
            "relative_humidity_2m": 60.0,
            "precipitation": 0.0,
            "wind_speed_10m": 10.0,
            "weather_code": 3,
            "soil_temperature_0_to_7cm": 22.0,
            "soil_moisture_0_to_7cm": 0.3
        },
        "daily": {},
        "timezone": "UTC"
    }

    mock_weather_llm.return_value = (
        "🌡 Temperature:\nWarm temperature is good.\n\n"
        "🌾 Irrigation:\nIrrigation is not required today."
    )
    mock_crop_llm.return_value = "Crop details generated by Crop Agent."
    mock_loc_llm.return_value = "Location crop suitability advice."
    mock_synth.return_value = "Cohesive agricultural advice response."

    mock_disease.return_value = (
        "🌿 Disease:\nHealthy Leaf\n\n"
        "🔍 Symptoms:\nThe leaf shows normal color.\n\n"
        "📊 Confidence:\nHigh"
    )

    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    print("\n" + "="*70)
    print("AGRICORE AI: INTEGRATION TEST SUITE - COORDINATOR AGENT")
    print("="*70)

    mock_image_path = BACKEND_DIR / "uploads" / "leaf.jpg"
    
    if mock_image_path.exists():
        try:
            mock_image_path.unlink()
        except OSError:
            pass

    # TEST 1: Weather
    print("\n--- TEST 1: Weather query with location coordinates ---")
    try:
        res_1 = process_request("Should I irrigate today?", image_path=None, latitude=20.2961, longitude=85.8245)
        print("RESULT:")
        print(f" - Agents Used: {res_1['agents_used']}")
        print(f" - Contains 'weather' response: {res_1['weather'] is not None}")
        
        assert "weather_agent" in res_1["agents_used"], "Test 1 Failed: 'weather_agent' not used."
        assert res_1["weather"] is not None, "Test 1 Failed: Weather data is None."
        print("[+] TEST 1 PASSED!")
    except Exception as e:
        print(f"[-] TEST 1 FAILED with exception: {e}")

    # TEST 2: Disease
    print("\n--- TEST 2: Disease query with uploaded image ---")
    create_mock_leaf_image(mock_image_path)
    try:
        res_2 = process_request("My tomato leaves have brown spots.", image_path=str(mock_image_path), latitude=None, longitude=None)
        print("RESULT:")
        print(f" - Agents Used: {res_2['agents_used']}")
        print(f" - Contains 'disease' response: {res_2['disease'] is not None}")

        assert "disease_agent" in res_2["agents_used"], "Test 2 Failed: 'disease_agent' not used."
        assert res_2["disease"] is not None, "Test 2 Failed: Disease data is None."
        print("[+] TEST 2 PASSED!")
    except Exception as e:
        print(f"[-] TEST 2 FAILED with exception: {e}")

    # TEST 3: Combined
    print("\n--- TEST 3: Combined query ---")
    try:
        res_3 = process_request("My tomato leaves have spots and should I irrigate today?", image_path=str(mock_image_path), latitude=20.2961, longitude=85.8245)
        print("RESULT:")
        print(f" - Agents Used: {res_3['agents_used']}")
        print(f" - Weather: {res_3['weather'] is not None} | Disease: {res_3['disease'] is not None}")

        assert "weather_agent" in res_3["agents_used"], "Test 3 Failed: 'weather_agent' not used."
        assert "disease_agent" in res_3["agents_used"], "Test 3 Failed: 'disease_agent' not used."
        print("[+] TEST 3 PASSED!")
    except Exception as e:
        print(f"[-] TEST 3 FAILED with exception: {e}")

    # TEST 4: Missing GPS
    print("\n--- TEST 4: Weather query with missing GPS coordinates ---")
    try:
        res_4 = process_request("Should I irrigate today?", image_path=None, latitude=None, longitude=None)
        print("RESULT:")
        print(f" - Response: {res_4}")
        assert "error" in res_4, "Test 4 Failed: No error returned."
        print("[+] TEST 4 PASSED!")
    except Exception as e:
        print(f"[-] TEST 4 FAILED with exception: {e}")

    # TEST 5: Missing Image
    print("\n--- TEST 5: Disease query with missing image path ---")
    try:
        res_5 = process_request("My crop leaf has a spot.", image_path=None, latitude=None, longitude=None)
        print("RESULT:")
        print(f" - Response: {res_5}")
        assert "error" in res_5, "Test 5 Failed: No error returned."
        print("[+] TEST 5 PASSED!")
    except Exception as e:
        print(f"[-] TEST 5 FAILED with exception: {e}")

    # TEST 6: Crop / General
    print("\n--- TEST 6: General crop inquiry ---")
    try:
        res_6 = process_request("Hello, I am a new farmer.", image_path=None, latitude=None, longitude=None)
        print("RESULT:")
        print(f" - Agents Used: {res_6['agents_used']}")
        assert "crop_agent" in res_6["agents_used"] or "general_agent" in res_6["agents_used"], "Test 6 Failed: 'crop_agent' not used."
        print("[+] TEST 6 PASSED!")
    except Exception as e:
        print(f"[-] TEST 6 FAILED with exception: {e}")

    if mock_image_path.exists():
        try:
            mock_image_path.unlink()
            print("\n[+] Cleaned up temporary mock leaf image.")
        except OSError:
            pass

    print("\n" + "="*70)
    print("ALL TESTS COMPLETED!")
    print("="*70 + "\n")

if __name__ == "__main__":
    run_tests()
